# Generated by Django 3.1.2 on 2020-12-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('student', 'STUDENT'), ('coordinator', 'COORDINATOR'), ('supervisor', 'SUPERVISOR'), ('admin', 'ADMIN')], max_length=100)),
                ('manage_users', models.BooleanField(default=False)),
                ('submit_tasks', models.BooleanField(default=False)),
                ('add_field_place', models.BooleanField(default=False)),
                ('view_field_place', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'User authorization',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField()),
                ('program', models.CharField(choices=[('Diploma', 'Diploma of official statistics'), ('Degree', "Bachelor's degree of official statistics"), ('supervisor', 'Field place supervisor'), ('lecturer', 'Lecturer'), ('administration', 'Admin')], max_length=20)),
                ('role_name', models.CharField(choices=[('student', 'STUDENT'), ('coordinator', 'COORDINATOR'), ('supervisor', 'SUPERVISOR'), ('admin', 'ADMIN')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
