# Generated by Django 3.1.2 on 2020-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(choices=[('BOS1', "Bachelor's degree of official statistics first year"), ('BOS2', "Bachelor's degree of official statistics second year"), ('lecturer', 'Lecturer'), ('administration', 'Admin')], max_length=20),
        ),
    ]
