# Generated by Django 3.1.7 on 2021-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201223_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthorization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='program',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role_name',
            field=models.CharField(choices=[('manager', 'MANAGER'), ('normal user', 'Normal user')], default='normal user', max_length=100),
        ),
    ]
