# Generated by Django 3.1.6 on 2021-03-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210315_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('sw', 'Swahili')], default='en-us', max_length=5),
        ),
    ]
