# Generated by Django 3.1.7 on 2021-03-16 14:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateField(default=datetime.datetime(2021, 3, 16, 14, 3, 0, 430442, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('requested_date', models.DateField(default=datetime.datetime(2021, 3, 16, 14, 3, 0, 430442, tzinfo=utc))),
                ('returnable', models.BooleanField(default=False)),
                ('destination', models.CharField(blank=True, max_length=300, null=True)),
                ('project_name', models.CharField(max_length=300)),
                ('request_status', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockapp.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateField(default=datetime.datetime(2021, 3, 16, 14, 3, 0, 430442, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockapp.product')),
            ],
            options={
                'verbose_name_plural': 'Products added',
            },
        ),
    ]
