# Generated by Django 3.1.6 on 2021-03-15 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_auto_20210311_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='destination',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='project_name',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='returnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 17, 47, 43, 37550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 17, 47, 43, 38547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 17, 47, 43, 38547, tzinfo=utc)),
        ),
    ]
