# Generated by Django 3.1.7 on 2021-03-16 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20210316_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 13, 6, 31, 128103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 13, 6, 31, 128103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 13, 6, 31, 128103, tzinfo=utc)),
        ),
    ]
